// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOGtYe44oBL1Y00sTAleoPyLfCA3kWFAs',
    appId: '1:68609157336:web:88e73502d83e56e8de0fad',
    messagingSenderId: '68609157336',
    projectId: 'trippo-81f0f',
    authDomain: 'trippo-81f0f.firebaseapp.com',
    storageBucket: 'trippo-81f0f.firebasestorage.app',
    measurementId: 'G-GC2HFQN1SB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG-YT1wQs4m4hwyv7g9f7y-z9-H388mc8',
    appId: '1:68609157336:android:39d75331e8cd3312de0fad',
    messagingSenderId: '68609157336',
    projectId: 'trippo-81f0f',
    storageBucket: 'trippo-81f0f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrLzRY8xWjg7Cy4t_D0ADZeX52f6gQviY',
    appId: '1:68609157336:ios:a1fab2272fefd69fde0fad',
    messagingSenderId: '68609157336',
    projectId: 'trippo-81f0f',
    storageBucket: 'trippo-81f0f.firebasestorage.app',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrLzRY8xWjg7Cy4t_D0ADZeX52f6gQviY',
    appId: '1:68609157336:ios:a1fab2272fefd69fde0fad',
    messagingSenderId: '68609157336',
    projectId: 'trippo-81f0f',
    storageBucket: 'trippo-81f0f.firebasestorage.app',
    iosBundleId: 'com.example.project1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOGtYe44oBL1Y00sTAleoPyLfCA3kWFAs',
    appId: '1:68609157336:web:b33d31c866bad02dde0fad',
    messagingSenderId: '68609157336',
    projectId: 'trippo-81f0f',
    authDomain: 'trippo-81f0f.firebaseapp.com',
    storageBucket: 'trippo-81f0f.firebasestorage.app',
    measurementId: 'G-R95TFJ6FQV',
  );
}
